# See https://github.com/unitycatalog/unitycatalog/blob/main/compose.yaml for the full compose file.
name: unitycatalog

services:

  unitycatalog:
    image: unitycatalog/unitycatalog:main-3172b4c
    hostname: unitycatalog
    container_name: unitycatalog
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./etc/conf/server.properties
        target: /home/unitycatalog/etc/conf/server.properties
      # todo add a long-term database here since it can 
      # trip up the process when spinning the environment back up.
      - type: volume
        source: unitycatalog_data
        target: /home/unitycatalog/etc/data
    networks:
      - unity

  marimo-spark:
    image: marimo-spark:latest
    hostname: marimo-spark
    container_name: marimo-spark
    #volumes:
    #  - type: bind
    #    source: ./marimo-playground/notebooks/
    #    target: /marimo-playground/notebooks/
    ports:
      - "2718:2718"
    networks:
      - unity

networks:
  unity:
    driver: bridge

volumes:
  # Persist docker volume across container restarts
  unitycatalog_data:
